ko_fi: razonyang
custom:
  - https://paypal.me/razonyang
  - https://raw.githubusercontent.com/razonyang/razonyang/main/images/alipay.png
  - https://raw.githubusercontent.com/razonyang/razonyang/main/images/wechat.png
