name: RSS
on:
  schedule:
    - cron: '* * * * *'
jobs:
  RSS:
    name: Update with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get RSS Feed
        uses: kohrongying/readme-the-rss@master
        with:
          feed_url: https://razonyang.com/zh-cn/index.xml
          count: 5
      - name: Commit file changes
        run: |
            git config --global user.name 'razonyang'
            git config --global user.email 'razonyang@gmail.com'
            git add .
            git diff --quiet --cached || git commit -m "Update README"    
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
